default_install_hook_types: [ pre-commit ]
default_stages: [ pre-commit ]
default_language_version:
  python: "3.14"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
      - id: mixed-line-ending
      - id: trailing-whitespace
        exclude: \.md$

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.6
    hooks:
      - id: remove-tabs

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.10.9
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.5
    hooks:
      - id: ruff-check
        args:
          - --fix
      - id: ruff-format

  - repo: https://github.com/PyCQA/bandit
    rev: 1.9.4
    hooks:
      - id: bandit
        exclude: |
          (?x)^(
            .*test.*\.py|
            .*/test/.*
          )$

  - repo: local
    hooks:
      - id: prune-stale-tags
        name: Prune local tags deleted on remote
        language: system
        entry: git fetch origin --prune --prune-tags --tags
        pass_filenames: false
        stages: [ manual ]

      - id: ty
        name: ty check
        entry: uv run ty check .
        language: system
        pass_filenames: false
        exclude: |
          (?x)^(
            .*test.*\.py|
            .*/test/.*
          )$
