default_install_hook_types: [ pre-commit ]
default_stages: [ pre-commit ]
default_language_version:
  python: "3.13"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-tabs

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        additional_dependencies: [ "types-redis", "fastapi", "pydantic"]

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.8.13
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
    -   id: ruff
        args:
        - --fix
        - --unsafe-fixes
    -   id: ruff-format

  - repo: https://github.com/netromdk/vermin
    rev: v1.6.0
    hooks:
      - id: vermin
        args: ['-t=3.13-', '--violations']

  - repo: local
    hooks:
      - id: prune-stale-tags
        name: Prune local tags deleted on remote
        language: system
        entry: git fetch origin --prune --prune-tags --tags
        pass_filenames: false
